apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s      # 每 15 秒抓取一次指標數據
      evaluation_interval: 15s

    scrape_configs:
      # 1. 讓 Prometheus 監控自己
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # 2. 自動發現並監控 K8s 叢集內所有的 Pod 指標 (包含你的前端、後端)
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name