sonar.projectKey=hsinyu1226_corporate-event-ticketing-system-team13
sonar.organization=hsinyu1226

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/.git/**,**/target/**,**/vendor/**

sonar.sourceEncoding=UTF-8

sonar.go.coverage.reportPaths=backend/coverage.txt
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.tests=backend,frontend/src
sonar.test.inclusions=backend/**/*_test.go,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/src/**/*.test.mjs

sonar.coverage.exclusions=load-test/**,frontend/e2e/**,frontend/src/test/**,frontend/src/main.tsx,backend/test_utils/**,backend/main.go,backend/bootstrap/**,backend/database/**,backend/pkg/storage/**,backend/pkg/redis.go,backend/model/**,backend/service/apperror/**,backend/repository/**,backend/pkg/utils.go,backend/pkg/scheduler.go